// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getLlmConfig: () => typedError<LlmConfig, IpcError>(__TAURI_INVOKE("get_llm_config")),
	getLlmApiKey: () => typedError<string, IpcError>(__TAURI_INVOKE("get_llm_api_key")),
	setLlmConfig: (input: SetLlmConfigInput) => typedError<LlmConfig, IpcError>(__TAURI_INVOKE("set_llm_config", { input })),
	// 用表单中的实时 endpoint + api_key（无需先保存）查询该 endpoint 支持的模型列表。
	listLlmModels: (input: ListLlmModelsInput) => typedError<string[], IpcError>(__TAURI_INVOKE("list_llm_models", { input })),
	// 用表单中的实时配置发一次最小请求（max_tokens=1）验证连通性。
	testLlmConnection: (input: TestLlmConnectionInput) => typedError<null, IpcError>(__TAURI_INVOKE("test_llm_connection", { input })),
	invokeLlmGeneration: (sessionId: string, themeCardId: string, channel: Channel<LlmStreamEvent>) => typedError<null, IpcError>(__TAURI_INVOKE("invoke_llm_generation", { sessionId, themeCardId, channel })),
	appendMessage: (input: AppendMessageInput) => typedError<Message, IpcError>(__TAURI_INVOKE("append_message", { input })),
	createSession: (input: CreateSessionInput) => typedError<Session, IpcError>(__TAURI_INVOKE("create_session", { input })),
	deleteSession: (sessionId: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_session", { sessionId })),
	listMessages: (sessionId: string) => typedError<Message[], IpcError>(__TAURI_INVOKE("list_messages", { sessionId })),
	listSessions: (themeCardId: string) => typedError<Session[], IpcError>(__TAURI_INVOKE("list_sessions", { themeCardId })),
	touchSession: (sessionId: string) => typedError<null, IpcError>(__TAURI_INVOKE("touch_session", { sessionId })),
	createThemeCard: (input: CreateThemeCardInput) => typedError<ThemeCard, IpcError>(__TAURI_INVOKE("create_theme_card", { input })),
	deleteThemeCard: (themeCardId: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_theme_card", { themeCardId })),
	getThemeCard: (themeCardId: string) => typedError<ThemeCard, IpcError>(__TAURI_INVOKE("get_theme_card", { themeCardId })),
	listThemeCards: () => typedError<ThemeCard[], IpcError>(__TAURI_INVOKE("list_theme_cards")),
	updateThemeCard: (input: UpdateThemeCardInput) => typedError<ThemeCard, IpcError>(__TAURI_INVOKE("update_theme_card", { input })),
};

/* Types */
export type AppendMessageInput = {
	sessionId: string,
	role: ChatRole,
	content: string,
};

export type ChatRole = "user" | "assistant" | "system";

export type CreateSessionInput = {
	themeCardId: string,
};

export type CreateThemeCardInput = {
	name: string,
	systemPrompt: string,
};

export type ErrorCategory = "Domain" | "Infra" | "Security" | "Gateway";

export type IpcError = {
	category: ErrorCategory,
	errorCode: string,
	message: string,
	retryable: boolean,
};

export type ListLlmModelsInput = {
	endpoint: string,
	apiKey: string,
};

export type LlmConfig = {
	endpoint: string,
	apiKeyRef: string,
	model: string,
	temperature: number | null,
	maxTokens: number | null,
	topP: number | null,
	frequencyPenalty: number | null,
	presencePenalty: number | null,
};

export type LlmStreamEvent = { type: "tokenChunk"; text: string } | { type: "completion"; fullText: string } | { type: "error"; errorCode: string; message: string; retryable: boolean };

export type Message = {
	id: string,
	role: ChatRole,
	content: string,
	createdAt: string,
};

export type Session = {
	id: string,
	themeCardId: string,
	createdAt: string,
	updatedAt: string,
	/**
	 *  最近一次被用户打开/查看的时间；None 表示从未被主动打开过（旧数据兼容）。
	 *  用于在打开 Theme Card 时自动跳转到最近打开的 Session。
	 */
	lastOpenedAt: string | null,
};

export type SetLlmConfigInput = {
	endpoint: string,
	apiKey: string,
	model: string,
	temperature: number | null,
	maxTokens: number | null,
	topP: number | null,
	frequencyPenalty: number | null,
	presencePenalty: number | null,
};

export type TestLlmConnectionInput = {
	endpoint: string,
	apiKey: string,
	model: string,
};

export type ThemeCard = {
	id: string,
	schemaVersion: number,
	name: string,
	systemPrompt: string,
	createdAt: string,
	updatedAt: string,
};

export type UpdateThemeCardInput = {
	themeCardId: string,
	name: string,
	systemPrompt: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

