// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getLlmConfig: () => typedError<LlmConfig, IpcError>(__TAURI_INVOKE("get_llm_config")),
	setLlmConfig: (input: SetLlmConfigInput) => typedError<LlmConfig, IpcError>(__TAURI_INVOKE("set_llm_config", { input })),
	invokeLlmGeneration: (sessionId: string, themeCardId: string, channel: Channel<LlmStreamEvent>) => typedError<null, IpcError>(__TAURI_INVOKE("invoke_llm_generation", { sessionId, themeCardId, channel })),
	appendMessage: (input: AppendMessageInput) => typedError<Message, IpcError>(__TAURI_INVOKE("append_message", { input })),
	createSession: (input: CreateSessionInput) => typedError<Session, IpcError>(__TAURI_INVOKE("create_session", { input })),
	listMessages: (sessionId: string) => typedError<Message[], IpcError>(__TAURI_INVOKE("list_messages", { sessionId })),
	createThemeCard: (input: CreateThemeCardInput) => typedError<ThemeCard, IpcError>(__TAURI_INVOKE("create_theme_card", { input })),
	getThemeCard: (themeCardId: string) => typedError<ThemeCard, IpcError>(__TAURI_INVOKE("get_theme_card", { themeCardId })),
	listThemeCards: () => typedError<ThemeCard[], IpcError>(__TAURI_INVOKE("list_theme_cards")),
};

/* Types */
export type AppendMessageInput = {
	sessionId: string,
	role: ChatRole,
	content: string,
};

export type ChatRole = "user" | "assistant" | "system";

export type CreateSessionInput = {
	themeCardId: string,
};

export type CreateThemeCardInput = {
	name: string,
	systemPrompt: string,
};

export type ErrorCategory = "Domain" | "Infra" | "Security" | "Gateway";

export type IpcError = {
	category: ErrorCategory,
	errorCode: string,
	message: string,
	retryable: boolean,
};

export type LlmConfig = {
	endpoint: string,
	apiKey: string,
	model: string,
};

export type LlmStreamEvent = { type: "tokenChunk"; text: string } | { type: "completion"; full_text: string } | { type: "error"; error_code: string; message: string; retryable: boolean };

export type Message = {
	id: string,
	role: ChatRole,
	content: string,
	createdAt: string,
};

export type Session = {
	id: string,
	themeCardId: string,
	createdAt: string,
	updatedAt: string,
};

export type SetLlmConfigInput = {
	endpoint: string,
	apiKey: string,
	model: string,
};

export type ThemeCard = {
	id: string,
	schemaVersion: number,
	name: string,
	systemPrompt: string,
	createdAt: string,
	updatedAt: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

